// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuaGBDOfNVn48oNhTLc8vTNN_6D_isjcU',
    appId: '1:82945796903:web:106090cbf589eb7cd51702',
    messagingSenderId: '82945796903',
    projectId: 'in-class-activity-13',
    authDomain: 'in-class-activity-13.firebaseapp.com',
    storageBucket: 'in-class-activity-13.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPkT2BBuOlteJRDvF6l6jnRuTqEUM9AZc',
    appId: '1:82945796903:android:6d37202fee060de1d51702',
    messagingSenderId: '82945796903',
    projectId: 'in-class-activity-13',
    storageBucket: 'in-class-activity-13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSWzZbwEtZbX5zCaJU_42eVdAJcEX0hs8',
    appId: '1:82945796903:ios:83b3c614ef77f155d51702',
    messagingSenderId: '82945796903',
    projectId: 'in-class-activity-13',
    storageBucket: 'in-class-activity-13.firebasestorage.app',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSWzZbwEtZbX5zCaJU_42eVdAJcEX0hs8',
    appId: '1:82945796903:ios:83b3c614ef77f155d51702',
    messagingSenderId: '82945796903',
    projectId: 'in-class-activity-13',
    storageBucket: 'in-class-activity-13.firebasestorage.app',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuaGBDOfNVn48oNhTLc8vTNN_6D_isjcU',
    appId: '1:82945796903:web:672167705647cf37d51702',
    messagingSenderId: '82945796903',
    projectId: 'in-class-activity-13',
    authDomain: 'in-class-activity-13.firebaseapp.com',
    storageBucket: 'in-class-activity-13.firebasestorage.app',
  );
}
